### PR TITLE
update the calendar indicator

### LINKED ISSUE #112: Update the calendar indicator
Google updated the date picker designs: http://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

### PR DESCRIPTION
**Pull request by eyelash**
fixes #112

There is a white one pixel border around the header, though. I'm not sure what is causing this.

### CODE REVIEW

**Comment by eyelash** [comment]
papyros-calendar

**Comment by VirusKA** [comment]
i kinda like that little white border :P looks cool!

**Comment by IdrissDimson** [comment]
im excited

**Comment by eyelash** [comment]
@VirusKA it is using the DatePicker component from QML Material that was introduced in papyros/qml-material#218

**Comment by IdrissDimson** [comment]
oh nice nice

**Comment by ricardomv** [comment]
Thanks :+1:

**Pull request merged**
